from .RF_example import RF_example
from .DNN_example import DNN_example
from .KNN_example import KNN_example
from .LogR_example import LogR_example
from .SVM_example import SVM_example
from .MLP_example import MLP_example
from .DT_example import DT_example
from .NB_example import NB_example
from .DTR_example import DTR_example
from .ET_example import ET_example
from .ETR_example import ETR_example
from .DigitRecognition_example import DigitRecognition_example