from .RF_example import RF_example
from .DNN_example import DNN_example
from .KNN_example import KNN_example
from .LogR_example import LogR_example
from .SVC_example import SVC_example
from .MLP_example import MLP_example
from .DT_example import DT_example
from .NB_example import NB_example
from .DTR_example import DTR_example
from .ET_example import ET_example
from .ETR_example import ETR_example
from .RN_example import RN_example
from .PA_example import PA_example
from .PAR_example import PAR_example
from .XGB_example import XGB_example
from .SVR_example import SVR_example
from .GBR_example import GBR_example
from .GBC_example import GBC_example
from .LR_example import LR_example
from .DigitRecognition_example import DigitRecognition_example