from .DNN_example import DNN_example
from .NB_example import NB_example
from .DTR_example import DTR_example
from .ETR_example import ETR_example
from .PAR_example import PAR_example
from .XGB_example import XGB_example
from .SVR_example import SVR_example
from .GBR_example import GBR_example
from .LR_example import LR_example